### ISSUE TITLE
Rails 3 compatibility broken

### ISSUE THREAD

**Issue by peterlong** [jwhitley/requirejs-rails#210]
The commit 913f599cbd436cefee48abfb72866ed621cc7062 adds lib/requirejs/rails/view_proxy.rb which has the line `include ActionView::Helpers::AssetUrlHelper` in it. This module does not exist in Rails 3.
It appears that it is included to get access to `javascript_path`. The same method is defined in `ActionView::Helpers::AssetTagHelper` in Rails 3. 

Perhaps compatibility could be restored with a code change like this:
```ruby
module Requirejs
  module Rails
    class ViewProxy
      include ActionView::Context
      if Rails.version.start_with?('4')
        include ActionView::Helpers::AssetUrlHelper 
        include ActionView::Helpers::TagHelper
      else 
        include ActionView::Helpers::AssetTagHelper
      end
    end
  end
end
```

AssetTagHelper includes TagHelper in Rails 3, so it need not be included again.

**Comment by froodian** [comment]
At the very least, the gemspec should be updated to state that Rails 4 is required.

**Comment by dtognazzini** [comment]
How about using [semver](http://semver.org/)?

**Comment by carsomyr** [comment]
All, could you point your `Gemfile`s to the master branch? If all is well, I'll make a new release.

**Comment by merqlove** [comment]
0.9.8 still fails at line 82:
wrong number of arguments (2 for 1)
```
  def javascript_path(source, options = {})
    if defined?(super)
      super # ERROR
    else
      view_proxy.javascript_path(source, options)
    end
  end
```

**Comment by agis-** [comment]
@merqlove Have you got the 0.9.9 working on your Rails 3.2 app, or is this issue present in 0.9.9 too?

**Comment by merqlove** [comment]
@agis- Yes, still present. And only my patch fixes it.

**Comment by agis-** [comment]
@merqlove I see, thanks. So you must have run on issues like #247 and [this](https://github.com/jwhitley/requirejs-rails/issues/248), or? If so, could you share some insight on how you've fixed them.

**Comment by merqlove** [comment]
@agis- I did pull request. #231

**Comment by agis-** [comment]
I'm kind of confused here, because your patch in #231 doesn't seem related to #247. However, I'm going to give it a try tomorrow and see how it goes.

**Comment by merqlove** [comment]
@agis- Yes, my patch is for #210 or something.

**Comment by agis-** [comment]
@merqlove Oh ok. My question in the previous comment was referring to whether you've stumbled on #247 and #248 issues too. Anyway, it seems you haven't.

Thanks anyway.

**Comment by merqlove** [comment]
@agis- Yeah, i have not tried 0.9.9 in production.
But in dev it works well.

**Comment by sun16** [comment]
Hi everyone,

In addition to the Rails 3.2 compatibility problems mentioned in the above comments, I found a problem in the almond build. A change in the rjs_driver template between [0.9.3](https://github.com/jwhitley/requirejs-rails/blob/0.9.3/lib/requirejs/rails/rjs_driver.js.erb) and [0.9.5](https://github.com/jwhitley/requirejs-rails/blob/0.9.5/lib/requirejs/rails/rjs_driver.js.erb) caused the almond build to output to almond.js instead of main.js in the tmp directory.

The fix to the above problem was to just use the older working 0.9.3 version.

It would be nice to specify in the readme that 0.9.5 (0.9.3 for Rails 3.2 + and almond) is the last known version with Rails 3 compatibility (possibly a gemspec constraint as well). Or do we intend to continue to support Rails 3.x?

**Comment by carsomyr** [comment]
@sun16 Almond support is screwed up right now. Does it work normally?

**Comment by sun16** [comment]
@carsomyr Sorry about the late response. I have just started using the latest Rails 4.2.5, so I can confirm that almond support is broken regardless of the Rails version. So to update my previous comment, almond support has been broken since 0.9.3, and it's unrelated to Rails 3.x compatibility.

I will create a separate PR for fixing this issue.

**Comment by carsomyr** [comment]
@sun16 Could you file a separate issue for this?

**Comment by sun16** [comment]
Sure, created #255 (have a PR #254 for fixing the almond build)
